name: Continuous Delivery

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build app
      run: dotnet build -c Release --no-restore

    - name: Publish
      run: dotnet publish ./WeatherForecast/WeatherForecast.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: api-artifact
        path: ${{ env.DOTNET_ROOT }}/api
        
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: api-artifact

    - name: Azure WebApp deploy
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'api-weatherforecast'
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
      
    

